version: '2'
services:
    jhipsterconf-app:
        image: jhipsterconf
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterconf-postgresql:5432/jhipsterConf
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterconf-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterconf-postgresql
